GET http://localhost:8000/members HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3b25lc3kiLCJleHAiOjE2NTYyNjc4MjcsInR5cGUiOiJhY2Nlc3MifQ.7M-RuXVxB1XcTZaXsZo68c8hhFAz5DgRpqXjg-ah8UQ

###

GET http://localhost:8000/members/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3b25lc3kiLCJleHAiOjE2NTYwODUyODYsInR5cGUiOiJhY2Nlc3MifQ.pFG8WJf1wXHF-czR1OyB985OYnAEVaveirBEWgIV_Ec

###

POST http://localhost:8000/members HTTP/1.1
content-type: application/json

{
    "username": "wonesy",
    "first_name": "Cameron",
    "last_name": "Johson",
    "email": "test@test.com",
    "registration_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHViIjoxLCJzdWIiOiJ3b25lc3kiLCJleHAiOjE3NDk0MTUwNjV9.jqfAPbUaIGX8YTA2hYV6R2rLCqB0ed9wkFbxtINhAl8",
    "password": "pass"
}

###

GET http://localhost:8000/members/foolingtook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3b25lc3kiLCJleHAiOjE2NTYwODUyODYsInR5cGUiOiJhY2Nlc3MifQ.pFG8WJf1wXHF-czR1OyB985OYnAEVaveirBEWgIV_Ec
