GET http://localhost:8000/members HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3b25lc3kiLCJleHAiOjE2NTYyNjc4MjcsInR5cGUiOiJhY2Nlc3MifQ.7M-RuXVxB1XcTZaXsZo68c8hhFAz5DgRpqXjg-ah8UQ

###

GET http://localhost:8000/members/wonesy HTTP/1.1

###

POST http://localhost:8000/members HTTP/1.1
content-type: application/json

{
    "username": "wonesy",
    "first_name": "Cameron",
    "last_name": "Jones",
    "email": "test@test.com",
    "password": "fakepassword"
}

###

PUT http://localhost:8000/members/camomile HTTP/1.1
content-type: application/json

{
    "username": "wonesy"
}
